05 lection3/01 tooltip
js-tasks-ru/htmlcss-20220519_lk pull request #14
Opened 2022-06-25 17:57 UTC by lk4n

Вариант с 4 цветами цветами и 2 позиционированиями

2022-06-25 17:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-25 19:25 UTC, GSemikozov requested changes

2022-06-25 19:25 UTC, GSemikozov commented on 05-lection3/01-tooltip/_tooltip.scss
> +@import './../../assets/css/main.scss';
не main импортируем в компонент, а наоборот т- компонент в main )

2022-06-26 11:55 UTC, lk4n commented on 05-lection3/01-tooltip/_tooltip.scss
> +@import './../../assets/css/main.scss';
Это сделано для ДЗ, чтобы подключить  переменные (sass) и миксины на этапе разработки.
Могу переменные sass выделить в отдельный файл, например, vars_sass.scss. И подключать их и миксины, вместо всего main.sсss. 
Т.е. index.html будет:
`<link rel="stylesheet" href="../../assets/css/main.css">`
в footer.scss:
```
@import './../../assets/css/mixins';
@import './../../assets/css/vars_sass';

.tooltip {
...
```

2022-06-26 20:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-26 21:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 21:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 22:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 09:37 UTC, GSemikozov commented on 05-lection3/01-tooltip/_tooltip.scss
> +@import './../../assets/css/main.scss';
да, z-index нужно добавить

2022-06-27 09:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 10:18 UTC, lk4n commented on 05-lection3/01-tooltip/_tooltip.scss
> +@import './../../assets/css/main.scss';
Добавил

2022-06-27 14:17 UTC, GSemikozov approved these changes

2022-06-27 14:18 UTC, merged