05 lection3/02 modal
js-tasks-ru/htmlcss-20220519_lk pull request #16
Opened 2022-07-15 18:48 UTC by lk4n

Привет.
JS для body не работал, исправил: 
`    document.body.overflow = 'hidden'; ` на `
    document.body.style.overflow = 'hidden';`
Добавил базовую aria для кнопки `modal__close` и body. Как я понял, арию `aria-hidden="true"` для элементов с `display:none` не надо добавлять, они все равно не отрисовуются, по этому для блока modal его не ставил.

2022-07-15 18:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-15 19:40 UTC, GSemikozov requested changes

2022-07-15 19:40 UTC, GSemikozov commented on components/modal/_modal.scss
> +  &:before {
не через before - сама модалка должна позиционироваться как fixed )

2022-07-16 02:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-16 02:09 UTC, lk4n commented on components/modal/_modal.scss
> +  &:before {
Исправил.

2022-07-16 20:04 UTC, GSemikozov approved these changes

2022-07-16 20:05 UTC, merged